### ISSUE TITLE
Receive-GitCommit Error

### ISSUE THREAD

**Issue by anandmukundan** [webmd-health-services/LibGit2.PowerShell#17]
I am using v0.9.2 via nugget in PS 5. 

When I call the Receive-GitCommit I am getting the following error.

Exception calling "Pull" with "2" argument(s): "Value cannot be null.
Parameter name: merger"
At \LibGit2\Functions\Receive-GitCommit.ps1:70 char:13
+             $repo.Network.Pull($signature, $pullOptions)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

**Comment by splatteredbits** [comment]
Where are you pulling from? Run

```
git config -l
```
and paste the relevant configuration.

**Comment by anandmukundan** [comment]
I am pulling from a remote.

I am running a command like Receive-GitCommit -RepoRoot $SourceDir inside an script. The $SourceDir is set to a directory which is a git repository. I get the above error.

If I run 
  Set-Location -Path $SourceDir
    git pull origin

The git command is able to pull from remote.

**Comment by splatteredbits** [comment]
What is the URI of the remote you're pulling from? I need to see your Git configuration to try to reproduce the problem. I can't reproduce it.

**Comment by anandmukundan** [comment]
Output from config below.. I just removed some info related to the URLs and recent repos from the config output..

$ git config -l
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
diff.astextplain.textconv=astextplain
rebase.autosquash=true
http.sslcainfo=C:/Program Files (x86)/Git/mingw32/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
pack.packsizelimit=2g
credential.helper=manager
alias.last=log -1 HEAD
gui.recentrepo=
gui.recentrepo=
gui.recentrepo=
core.bare=false
core.repositoryformatversion=0
core.filemode=false
core.symlinks=false
core.ignorecase=true
core.logallrefupdates=true
remote.origin.url=http://
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.feature/xxx.remote=origin

**Comment by anandmukundan** [comment]
I am pulling from an internal git server and that I why I removed the origin url. I will try today with a public git repository.

**Comment by anandmukundan** [comment]
I tried doing this with LibGit repository.. I updated to the latest version to see if I get anything different.

PS C:\Anand\Test\LibGit2.PowerShell> git config -l
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
diff.astextplain.textconv=astextplain
rebase.autosquash=true
core.symlinks=false
core.autocrlf=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
pack.packsizelimit=2g
help.format=html
http.sslcainfo=/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
alias.last=log -1 HEAD
gui.recentrepo=
gui.recentrepo=
gui.recentrepo=
user.name=Anand Mukundan
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/webmd-health-services/LibGit2.PowerShell.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
PS C:\Anand\Test\LibGit2.PowerShell> Receive-GitCommit
Exception calling "Pull" with "3" argument(s): "Value cannot be null.
Parameter name: merger"
At xxxx\LibGit2.PowerShell.0.10.1\LibGit2\Functions\Receive-GitCommit.ps1:69 c
+             [LibGit2Sharp.Commands]::Pull($repo, $signature, $pullOpt ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

I suspect this may have something to do with the network as I am behind a firewall. If I switch to a different network (not firewalled), then I get certificate error and not this error. But "git pull" does not seem to have a problem in both cases.

Is there some way to check what error/stacktrace that is being generated apart from the PS output?

**Comment by anandmukundan** [comment]
Ok, I did take a look at libgit code and after debugging found that if email is not setup in git, libgit fails to build a default signature. The PS module calls this function when a before a receive and that returns an null object. So the Receive will fail with this error.
