### ISSUE TITLE
Docs link in README points to empty page?

### ISSUE THREAD

**Issue by felixfbecker** [webmd-health-services/LibGit2.PowerShell#27]
The link in the README points to http://www.get-gitautomation.org/ which is empty except a copyright:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/10532611/43792865-411f64b4-9a7a-11e8-8c47-c3fb233e3669.png">

I found http://get-libgit2.org/ in the Wiki but that seems to use an old package name?

**Comment by splatteredbits** [comment]
The next time our team is working on GitAutomation, we'll remove that link.

**Comment by JohnyWS** [comment]
Is this package genuine and have you been hacked? The http://get-libgit2.org now points to some chinese website?!

**Comment by decoyjoe** [comment]
@JohnyWS This package is still genuine, we have not been hacked. I have removed all references to the domains `get-gitautomation.org` and `get-libgit2.org`, which we do not own.

CC: @splatteredbits
