### ISSUE TITLE
"malformed URL '...'" when using URLs containing non-URLEncoded expressions

### ISSUE THREAD

**Issue by thorbenw** [webmd-health-services/LibGit2.PowerShell#32]
`ConvertTo-GitFullPath` should return `$Uri.AbsoluteUri` instead of `$Uri.ToString()` if `$Uri.Scheme` is detected in parameter set _Uri_. `ToString()` removes URL encodings, while `AbsoluteUri` even adds them automatically (less error prone, almost sort of fail safe, more convenient anyway and afaik doesn't consume extra resources due to being already evaluated during parsing/construction).

https://github.com/webmd-health-services/GitAutomation/blob/36cc9a31df01ccc4aafbc8e250053e9287843417/GitAutomation/Functions/ConvertTo-GitFullPath.ps1#L35

**Comment by decoyjoe** [comment]
@thorbenw This issue is fixed in the [0.13.0](https://www.powershellgallery.com/packages/GitAutomation/0.13.0) release.
